# Generated by Django 4.1.2 on 2022-10-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_title', models.CharField(max_length=120)),
                ('field_name', models.FileField(blank=True, max_length=254, null=True, upload_to='uploads/')),
            ],
        ),
    ]
