# Generated by Django 4.1.2 on 2022-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomefieldModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.FileField(blank=True, max_length=254, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homeviewmodel',
            name='field_name',
        ),
    ]
