# Generated by Django 4.1.2 on 2022-10-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_homefieldmodels_remove_homeviewmodel_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homefieldmodels',
            options={'verbose_name': 'Home Resume', 'verbose_name_plural': 'Home Resumes'},
        ),
        migrations.AlterModelOptions(
            name='homeviewmodel',
            options={'verbose_name': 'Home Name', 'verbose_name_plural': 'Home Names'},
        ),
        migrations.AlterField(
            model_name='homefieldmodels',
            name='field_name',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='media/'),
        ),
    ]
